### 음식 이미지 업로드 presigned-url 생성 API
POST {{url}}/api/v1/meals/images/presigned-url
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "contentType": "image/jpeg",
  "fileSizeBytes": 1000
}

### 발급받은 presigned url로 이미지 S3에 업로드
PUT https://nyummy-app-bucket-455615001241-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com/temp/9ab1af40-c687-4303-945f-f63d385724a1.jpg?
    x-id=PutObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&
    X-Amz-Credential=AKIAWUFGFGKM4PNRWFHW%2F20260806%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Date=20260806T060626Z&
    X-Amz-Expires=600&X-Amz-SignedHeaders=content-type%3Bhost&
    X-Amz-Signature=cae3ff97e2d3ac2c9b6278f4d6ca3127f27f1bf06674f9054eb828fc4196a0ac
Content-Type: image/jpeg

< image/really_crazy.jpg


### 식사기록 생성 API
POST {{url}}/api/v1/meals
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "really_crazy",
  "imageKey": "temp/9ab1af40-c687-4303-945f-f63d385724a1.jpg",
  "mealAt": "2026-07-20T07:12:26Z",
  "iconId": 1
}

### 분석 상태 조회 API
@mealId = 11
GET {{url}}/api/v1/meals/{{mealId}}/analysis
Authorization: Bearer {{token}}

### 재분석 요청 API
POST {{url}}/api/v1/meals/{{mealId}}/analysis
Authorization: Bearer {{token}}